### ISSUE TITLE
Sinhala typing in LibreOffice is "wobbly" when typing vowel signs

### ISSUE THREAD

**Issue by lohang** [fcitx/fcitx5-m17n#2]
**Description**
Sinhala typing with fcitx5-m17n in LibreOffice is "wobbly" when typing vowel signs. Not as comfortable as the experience in a text editor (emails or gedit), or when typing with Ibus in a similar setting, in LibreOffice. The typing experience creates discomfort to the eyes because the letters/vowel signs make jerky movements forward and backward. At times there are awkward gaps between the letters and vowel signs, and sometimes vowel signs are shown at the wrong place until you move to the next letter or hit space.

**How to reproduce**
1. Start LibreOffice Writer (Version: 6.0.7.3)
2. Switch to wijesekera (M17N)
3. Try to type the following line:
isxy, NdIdfjka ,shd f,dalhg m`odkh lsrSu'

**Actual typing experience**
The typing experience creates discomfort to the eyes because the letters/vowel signs make jerky movements forward and backward.
![fcitx_libreoffice](https://user-images.githubusercontent.com/78773934/108989494-a68aac80-76bb-11eb-9cf7-b4b0a22dd6e5.png)

https://user-images.githubusercontent.com/78773934/108990118-71328e80-76bc-11eb-991e-9e367db6cf3a.mp4

**Expected experience (example created using Ibus and LibreOffice)**
![ibus_libreoffice](https://user-images.githubusercontent.com/78773934/108989533-b0acab00-76bb-11eb-8b5c-85e997d6cdf1.png)

https://user-images.githubusercontent.com/78773934/108990557-0897e180-76bd-11eb-891d-39f99c15a00c.mp4

**Desktop:**
    Desktop: GNOME 3.28.2, Ubuntu 18.04.5
    Display server type: X11

**Comment by wengxt** [comment]
So first of all, I could not reproduce this on latest libreoffice on my system (Archlinux), so looks like they already fix it upstream.

The issue itself is actually libreoffice tries to apply "underline" to the preedit text. Before the workaround (https://github.com/fcitx/fcitx5-m17n/commit/44742ddd4c886638b4aa8bbd58d3c7dc2805c1d3), fcitx sends the text without any format. Somehow in this version of libreoffice would apply underline to the first character. This makes the vowel and the letter have two different format, so it can not merge them together.

The workaround is always set underline format on the fcitx side so they share the same format and libreoffice would then be able to merge it.
