### ISSUE TITLE
Some files (test/test*) are licensed under GPL-2.0-or-later, not LGPL-2.1+

### ISSUE THREAD

**Issue by hosiet** [fcitx/fcitx5-m17n#3]
README.md claims that "All codes are currently licensed in LGPL 2.1+". However, some files under `test` dir is still licensed under GPL-2.0-or-later. We should update description accordingly.

**Comment by hosiet** [comment]
Also test/testdir.h.in

**Comment by wengxt** [comment]
@hosiet Though I don't think it really matters for packaging. test code doesn't go into the installed compiled binary.
