### ISSUE TITLE
using non-ASCII characters in input sequence (m17n?)

### ISSUE THREAD

**Issue by wengxt** [fcitx/fcitx5-m17n#4]
### Discussed in https://github.com/fcitx/fcitx5/discussions/999

<div type='discussions-op-text'>

<sup>Originally posted by **silmeth** March 27, 2024</sup>
Hi, I’ve recently tried to move from ibus to fcitx5 and thus I tried to migrate my [Cyrillic ibus-table](https://github.com/silmeth/ms-cyrillic-ibus-table) input method to m17n so that I could use it in fcitx. The first attempt can be seen [in my dotfiles on gitlab](https://gitlab.com/silmeth/configs/-/blob/master/keyboard/.m17n.d/interslavic-cyrillic.mim).

But I have a problem. I use Polish keyboard as my main default keyboard layout – and Polish layout lets me input characters like ⟨ż⟩ via <kbd>AltGr</kbd> + <kbd>z</kbd>, or ⟨ę⟩ via <kbd>AltGr</kbd> + <kbd>e</kbd> – and I did use those in the input sequences to transform them into Cyrillic ⟨ж⟩ and ⟨ѧ⟩ respectively.

So I added rules like these to my mapping:

```sexp
    ("Ż" ?Ж)
    ("ż" ?ж)
```

but they don’t work – when I switch the input method to my Cyrillic, hitting <kbd>AltGr</kbd> + <kbd>z</kbd> produced unchanged Polish ⟨ż⟩.

The [m17n data format spec](https://www.nongnu.org/m17n/manual-en/m17nDBFormat.html#mdbIM) says about `KEYSEQ`:

> `MTEXT` in the definition of `KEYSEQ` consists of characters that can be generated by a keyboard. Therefore `MTEXT` usually contains only `ASCII` characters. However, if the input method is intended to be used, for instance, __with a West European keyboard, `MTEXT` may contain Latin-1 characters__.

so I’d expect this to work. Is this a bug in fcitx5, a consciously enforced limitation? Is there a way around it?

I also tried making rules with modifier keys explicitly myself, eg:
```sexp
    ((A-z) ?ж)
```
and this lets me use the left <kbd>Alt</kbd> but not the right one, I also tried:
```sexp
    ((G-z) ?ж)
```
(`G-` is the m17n prefix for AltGr) but this does nothing with my Polish keyboard layout.</div>

**Comment by wengxt** [comment]
@silmeth so basically let me describe what fcitx5-m17n currently does:
It converts a key based on the layout with X symbol, when AltGr is pressed, "G-" prefix will be prepended.

So, for example, with pl, AltGr + Z will be interpreted as "G-zabovedot". I don't know if this is right, or wrong, because no m17n-db file expect to get this.

But if I write ((S-G-Zabovedot) ?Ж) , then it indeed work. So yeah, it works, but not in a way you think.

I can indeed convert it in whatever way I want, but I doubt whether m17n knows zabovedot can be mapped to "ż", because if you grep through "zabovedot" in m17n-db or m17n-lib, there's no match.

Also, m17n-edit can't also do it.. so it's totally unclear on what "should" be done.

If you need multiple key, you can write e.g. `((G-zabovedot G-zabovedot) ....)`

So I think if you're fine with adjusting your file, it can be made to work.

Also, as for your case, I would suggest that you enforce your m17n table with a certain layout. This can be easily done with fcitx gui tool (click the keyboard button on the input method (kcm) or when input method is selected (configtool) ). So you don't need to bother whether you need to make it work with pl or us, but just focus on us layout.

If you want to see what does fcitx convert the key it get

You either start with `fcitx5 --verbose=m17n=5`

Or with any dbus tool to change a runtime instance.
```
qdbus org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.SetLogRule m17n=5
```

Since current logic doesn't really prevent you from implement such a table, I have no intention to change it.

**Comment by wengxt** [comment]
How to enforce a different layout for certain input method:
![图片](https://github.com/fcitx/fcitx5-m17n/assets/259684/fc09fa23-e2e2-4abe-92f1-8acf5d35a2aa)

**Comment by silmeth** [comment]
@wengxt I have a few issues with this approach:

1. m17n documentation says that:
   > `MTEXT` in the definition of `KEYSEQ` consists of characters that **can be generated** by a keyboard. Therefore `MTEXT` **usually** contains only ASCII characters. **However**, if the input method is intended to be used, for instance, with a West European keyboard [but my understanding is that others are allowed as well], `MTEXT` **may contain** Latin-1[ie. non-ASCII] characters.

   I understand this as saying that m17n allows stuff like `ż` in their `KEYSEQ` literals and I’d expect this to work (writing `"ż"` and not `(G-zdotabove)`).
2. I **do not** want my layout to be tied to a specific layout (Polish in this case). That’s why my original table layout used all kinds of letters, among them `ż`, `ž`, and also ASCII sequences `zx` and `zs` as valid possible inputs to make the ⟨ж⟩ character. The intention is that it’d be useful to anyone with *any* Slavic keyboard layout, allowing them to input the Cyrillic character using their preferred way of inputting *their* Latin equivalent of the Cyrillic character, on *their* keyboard – be it Polish, Czech, Croatian, or else. Polish layout with AltGr + Z was just an example.

So while the work-around works for me individually, I still think it’s a larger problem in the m17n system.

**Comment by wengxt** [comment]
m17n-lib understand only part of key sym to text conversion. E.g. key pad key, like KP_{1..9}, it doesn't understand it can be mapped to "1" .. "9". This can be actually a nice thing. It allows KP_1 and Key 1 to do different things, kn-kgp 1 and KP_1 will do different things. While bn-disha KP_1 and "1" will do the same thing by having two different rule to match (KP_1) and "1".

As for "(G-", there are some mim file relies on this. E.g. "mni-inscript2-beng" has rule like "mni-inscript2-beng.mim:  ((G-x) "৺") , which means, if you make "G-x" and "x" equivalent, since without such rule it should produce text "x" too,

You'll not be able to do things like
```
   ("X" "ঁ")
   ("x" "ং")
   ((G-x) "৺")
 ```

Also per-m17n document, the "..." is only a short hand for ascii only sequence. So looks like it conflict with itself about "latin-1" thing.

```
KEYSEQ specifies a sequence of keys in this format:

  (SYMBOLIC-KEY SYMBOLIC-KEY ...)

where SYMBOLIC-KEY is the keysym value returned by the xev command. For instance

  (n i)

represents a key sequence of <n> and <i>. If all SYMBOLIC-KEYs are ASCII characters, you can use the short form

  "ni"
```

Now, the final thing, in m17n-lib own code:
https://git.savannah.nongnu.org/cgit/m17n/m17n-lib.git/tree/src/m17n-X.c?id=cd9b5e3d1af6b4ba6cb9d1ea1fe87975a7cb04ff#n2009

https://git.savannah.nongnu.org/cgit/m17n/m17n-lib.git/tree/src/input-gui.c?id=cd9b5e3d1af6b4ba6cb9d1ea1fe87975a7cb04ff#n728

minput_event_to_key will call to mwin__parse_event only has special code for "removing Shift" for ascii key, and altgr is always retained. 

Fcitx's engine only replicate the upstream m17n code logic here. Well, that's how m17n designed. Fcitx it only a downstream project so it will only follow what upstream does. If you have other opinion, you should report the issue to upstream first.
